# Generated by Django 3.0.4 on 2020-03-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('code', models.TextField(max_length=10000)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('input', models.TextField(blank=True, max_length=100)),
                ('output', models.TextField(blank=True, max_length=100)),
                ('make_public', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='myscripts/')),
                ('working_code', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('coder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Coder')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Problem')),
            ],
        ),
    ]
