# Generated by Django 3.0.3 on 2020-04-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import share.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumb_nail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.FileField(upload_to=share.models.user_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Photo'),
        ),
    ]
