# Generated by Django 3.0.3 on 2020-04-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_media_thumb_nail'),
        ('share', '0007_auto_20200419_1411'),
    ]

    operations = [
    ]
