# Generated by Django 3.0.4 on 2020-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20200425_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='page_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
