# Generated by Django 3.0.3 on 2020-04-30 00:47

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_auto_20200426_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=share.models.user_directory_path),
        ),
    ]
