# Generated by Django 3.0.3 on 2020-04-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0018_auto_20200430_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Photo'),
        ),
    ]
