# Generated by Django 3.0.3 on 2020-05-02 10:02

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0019_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='user_icon.png', upload_to=share.models.user_directory_path),
        ),
    ]
