# Generated by Django 3.0.4 on 2020-05-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0020_userlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
