# Generated by Django 3.0.4 on 2020-05-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0022_friend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
