# Generated by Django 3.0.4 on 2020-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0024_auto_20200503_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
